<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net5.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <AssemblyName>JxrConverter</AssemblyName>
    <RootNamespace>JxrConverter</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="..\jxr_to_png_\jxr_to_png.exe">
      <LogicalName>jxr_to_png.exe</LogicalName>
    </EmbeddedResource>
  </ItemGroup>

</Project>
